#board, selected, nº remaining moves, goal

LEVELS = {
    1:[
        [
            0,0,
            'red',
            'red',0,
            'red','green',
            0,0,0,'green',0,
            'blue','green',
            'blue',0,
            'blue',
            0,0
            ], 0, 9,
            [
            0,0,
            0,
            0,'yellow',
            0,0,
            0,'purple','white',0,0,
            0,0,
            0,'cyan',
            0,
            0,0
            ]
    ],
    2:[
        [   
            0,0,
            0,
            0,0,
            0,0,
            0,0,'white',0,0,
            0,0,
            'green',0,
            'white',
            'blue',0
            ], 0, 13,
            [
            0,0,
            0,
            0,0,
            0,0,
            0,0,'white',0,0,
            0,0,
            'white',0,
            'green',
            0,'blue'
            ]
    ],
    3:[
        [   
            'yellow','white',
            'green',
            'green','white',
            'green','blue',
            'white','white',0,'blue','cyan',
            'red','blue',
            'red','white',
            'red',
            'purple','white'
            ], 0, 16,
            [
            'cyan','white',
            'green',
            'green','white',
            'green','blue',
            'white','white',0,'blue','purple',
            'red','blue',
            'red','white',
            'red',
            'yellow','white'
            ]
    ],
    4:[
        [   
            0,0,
            0,
            0,0,
            0,0,
            0,0,0,0,0,
            0,0,
            0,0,
            0,
            0,0
            ], 0, 0,
            [
            0,0,
            0,
            0,0,
            0,0,
            0,0,0,0,0,
            0,0,
            0,0,
            0,
            0,0
            ]
    ],
    5:[
        [   
            0,0,
            0,
            0,0,
            0,0,
            0,0,0,0,0,
            0,0,
            0,0,
            0,
            0,0
            ], 0, 0,
            [
            0,0,
            0,
            0,0,
            0,0,
            0,0,0,0,0,
            0,0,
            0,0,
            0,
            0,0
            ]
    ]
}